In [1]:
import numpy as np

In [2]:
#matris
A=[[1,2,3],[4,5,6]]

In [3]:
print(A)

[[1, 2, 3], [4, 5, 6]]


In [4]:
B=np.array([[2,4,6],[1,3,5]])
print(B)

[[2 4 6]
 [1 3 5]]


In [5]:
array=np.zeros((2,4))

In [6]:
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
array2=np.ones((1,6))

In [8]:
print(array2)

[[1. 1. 1. 1. 1. 1.]]


In [9]:
array3=np.eye(4)

In [10]:
print(array3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#return random integers
array4=np.random.randint(20)
print(array4)

4


In [17]:
array5=np.random.randn(10)
print(array5)

[-0.74980131 -1.17379    -0.1912139   0.91627759  1.33045118  0.70473063
  0.27190001 -0.97564123 -0.54031814  0.61883259]


In [18]:
array6=np.random.rand(5)
print(array6)

[0.10435579 0.36338956 0.80568586 0.71375071 0.3691737 ]


In [21]:
array7=np.matrix('1 2; 3 4;6 7')
print(array7)

[[1 2]
 [3 4]
 [6 7]]


In [22]:
adet=int(input("kaç tane sayı girilecek?"))
max=0
for i in range(0,adet):
    sayi=int(input("sayi gir "))
    if sayi > max:
        max=sayi

print("en büyük sayı: ",sayi)

kaç tane sayı girilecek?3
sayi gir 5
sayi gir -9
sayi gir 7
en büyük sayı:  7


In [23]:
adet=int(input("kaç tane sayı girilecek?"))

kaç tane sayı girilecek?4


In [24]:
max=0

In [ ]:
for i in range(0,adet):
    sayi=int(input("sayi gir "))
    if sayi > max:
        max=sayi

print("en büyük sayı: ",sayi)